packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

overrides:
  "@radix-ui/react-slot": "1.3.0-rc.1781217402884"

allowBuilds:
  "@firebase/util": true
  "@prisma/engines": true
  "@scarf/scarf": false
  argon2: true
  msgpackr-extract: false
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@firebase/util"
  - "@prisma/engines"
  - argon2
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - "@scarf/scarf"
