packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

overrides:
  "@radix-ui/react-slot": "1.3.0-rc.1781217402884"

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": false
  argon2: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - argon2
  - prisma
  - unrs-resolver

ignoredBuiltDependencies:
  - "@scarf/scarf"
