name: scilab

services:
  api:
    build:
      context: ../..
      dockerfile: services/api/Dockerfile
    container_name: scilab-api
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.scilab-api-http.entrypoints=http
      - traefik.http.routers.scilab-api-http.rule=Host(`scilab-api.epsilon.io.vn`)
      - traefik.http.routers.scilab-api-http.service=scilab-api
      - traefik.http.services.scilab-api.loadbalancer.server.port=80
    environment:
      - NODE_ENV=production
      - PORT=80
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/scilab?schema=public
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
      - SERVICE_FQDN_API
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: scilab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: scilab
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok
    command: ["postgres", "-c", "timezone=Asia/Bangkok"]
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scilab"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: scilab-postgres-data
